require: rubocop-rails

AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - db/files_schema.rb
    - config/**/*
    - vendor/**/*
    - bin/*
    - Gemfile.lock
  NewCops: disable

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/ApplicationController:
  Exclude:
    - spec/**/*

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Metrics/AbcSize:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - local
